---
global:
  marketplace-ami: false
  owner: jliang01@fortinet.com
  qsname: quickstart-fortinet-fortigate
  regions:
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
    - ap-south-1
    - ap-northeast-2
    - ap-southeast-1
    - ap-southeast-2
    - ap-northeast-1
    - ca-central-1
    - eu-central-1
    - eu-west-1
    - eu-west-2
    - eu-west-3
    - sa-east-1
  reporting: true
tests:
  scenario-all-regions:
    parameter_input: input.json
    template_file: workload-master.template
#  scenario-us:
#    parameter_input: input.json
#    template_file: workload-master.template
#    regions:
#      - us-east-1
#      - us-east-2
#      - us-west-1
#      - us-west-2
#  scenario-sa:
#    parameter_input: input.json
#    template_file: workload-master.template
#    regions:
#      - sa-east-1
#  scenario-ap:
#    parameter_input: input.json
#    template_file: workload-master.template
#    regions:
#      - ap-south-1
#      - ap-northeast-2
#      - ap-southeast-1
#      - ap-southeast-2
#      - ap-northeast-1
#  scenario-ca:
#    parameter_input: input.json
#    template_file: workload-master.template
#    regions:
#      - ca-central-1
#  scenario-eu:
#    parameter_input: input.json
#    template_file: workload-master.template
#    regions:
#      - eu-central-1
#      - eu-west-1
#      - eu-west-2
#      - eu-west-3

